version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:JO9N4IzhKVr7wYiDze8l@db-movies.cw3yi8ice1tm.us-east-1.rds.amazonaws.com:5432/movie_db
    volumes:
      - .:/app

volumes:
  postgres_data:
