FROM public.ecr.aws/lambda/python:3.11

ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /var/task

# Copy dependencies
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy application files
COPY . .

# Set the Lambda handler
ENTRYPOINT [ "python", "-m", "awslambdaric", "app.main.lambda_handler" ]
