"""add index to the  rating column to movies

Revision ID: ad5623016e1d
Revises: f9852add4db0
Create Date: 2025-07-21 19:53:38.087882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ad5623016e1d'
down_revision: Union[str, Sequence[str], None] = 'f9852add4db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_movies_rating'), 'movies', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_rating'), table_name='movies')
    # ### end Alembic commands ###
